name: carbonate_explorer
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - notebook
  - voila=0.5.5
  - ipywidgets=8.1.1
  - jupyterlab_widgets
  - plotly=5.18.0
  - pyco2sys=1.8.3.4
  - numpy
  - pandas
  - matplotlib
  - nbconvertan